### ISSUE TITLE
where to get vggface.h5?

### ISSUE THREAD

**Issue by JiaquanYe** [Anurag14/accessfaceid#30]
hello, where to get vggface.h5? thankyou

**Comment by Anurag14** [comment]
Hi! I did not upload vggface weights to avoid bloating the code. You can find weights on my google drive [here](https://drive.google.com/file/d/19q0fe9sZPYJMfabUeFs1lRtgE8c16tQC/view?usp=sharing).
I am closing this issue for now. if any more pointers are needed please feel free to ask.

**Comment by Anurag14** [comment]
Please try and use this link instead https://drive.google.com/file/d/19q0fe9sZPYJMfabUeFs1lRtgE8c16tQC/view?usp=sharing
Really sorry for inconvinience
